from argparse import ArgumentParser


def parse_args():
    parser = ArgumentParser()
    parser.add_argument("--train_src_file", type=str)
    parser.add_argument("--train_tgt_file", type=str)
    parser.add_argument("--device_count", type=int)
    parser.add_argument("--src_max_length", type=int)
    parser.add_argument("--tgt_max_length", type=int)
    parser.add_argument("--batch_size", type=int)
    parser.add_argument("--num_dataloader_worker", type=int)
    parser.add_argument("--shuffle_training_set", action="store_true")
    parser.add_argument("--dev_src_file", type=str)
    parser.add_argument("--dev_tgt_file", type=str)
    parser.add_argument("--warmup_step", type=int)
    parser.add_argument("--d_model", type=int)
    parser.add_argument("--nhead", type=int)
    parser.add_argument("--num_encoder_layers", type=int)
    parser.add_argument("--num_decoder_layers", type=int)
    parser.add_argument("--dim_feedforward", type=int)
    parser.add_argument("--transformer_dropout", type=float)
    parser.add_argument("--pe_dropout",type=float)
    parser.add_argument("--tgt_vocab_size", type=int)
    parser.add_argument("--epoch", type=int)
    parser.add_argument("--log_dir",type=str)
    parser.add_argument("--finetune_src_bert",action='store_true')
    parser.add_argument("--finetune_tgt_bert",action='store_true')
    return parser.parse_args()
